# Generated by Django 5.0.1 on 2024-01-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_supplier_product_product_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
