# Generated by Django 5.0.1 on 2024-01-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_pricehistory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['start'], 'verbose_name_plural': 'Price histories'},
        ),
    ]
