name: Django CI

env:
  SECRET_KEY: 'actions-secret-key'
  DEBUG: true
  CELERY_BROKER_URL: 'redis://broker:6379/'

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]
        redis-version: [7]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Start Redis Server
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}
          redis-container-name: broker
          redis-port: 6379

      - name: Install Dependencies
        run: |
          pip install --upgrade pip poetry
          poetry install

      - name: Start Celery Worker
        run: |
          poetry run celery -A core worker -l INFO

      - name: Run Tests
        run: |
          poetry run python3.12 manage.py test apps